version: '3'
services:
  client_web:
    image: nginx:latest
    container_name: client_web
    ports: 
      - "80:80"
    volumes:
      - ./client/proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  client:
    build:
      context: ./client
    container_name: client
    expose: 
      - "8080"
    volumes:
      - ./client/source:/app
      - /app/node_modules
    restart: "unless-stopped"
  server_web:
    image: nginx:latest
    container_name: server_web
    ports: 
      - "3000:3000"
    volumes:
      - ./server/proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  server:
    build:
      context: ./server
    container_name: server
    expose:
      - "3000"
    volumes:
      - ./server/source:/app
      - /app/node_modules
    restart: "unless-stopped"
